#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
    inputs:
      Reason:
        description: 'Reason for build'
        required: true
        default: 'just cause'
      tags:
        description: 'Test scenario tags'
        required: false
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK v 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          echo "Reason for build: ${{ github.event.inputs.Reason }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Where am I"
          pwd
          echo "What's here? "
          ls -lAh
      - name: Building with Maven Wrapper
        run: |
          cd project
          ./mvnw clean install
